name: "Build Armbian SWL"
on:
  workflow_dispatch:
    # manual trigger
  schedule:
    # runs every day at 3am UTC
    - cron: '0 3 * * *' 

jobs:

  Keep:
    name: "Keep alive"
    runs-on: ubuntu-latest
    steps:
      # checkout this repository
      - uses: actions/checkout@v4
      # prevent GitHub from suspending cronjob
      - uses: gautamkrishnar/keepalive-workflow@v1 

  WSL:
    # we need to deal with this separate as here we have different extensions
    strategy:
      fail-fast: false
      matrix:
        board: [wsl2-arm64,wsl2-x86]
        os: ["jammy"]
        
    name: "${{ matrix.os }},${{ matrix.board }}${{ matrix.extension }}"
    runs-on: ubuntu-latest
    steps:

      - uses: igorpecovnik/build@main # #uses: armbian/build@AR-1459
        with:
          # mandatory
          armbian_token:              "${{ secrets.GITHUB_TOKEN }}"          # GitHub installation access token
          armbian_target:             "kernel"                               # build configuration from userpatches
          armbian_release:            "${{ matrix.os }}"                     # userspace: jammy, bookworm, trixie, etc.
          armbian_board:              "${{ matrix.board }}"                  # board build target
          armbian_artifacts:          "build/output/debs/"                   # board build target
          # optional
          armbian_release_tittle:     "Armbian SDK"                          # release tittle
          armbian_release_body:       "Virtual images for x86 and arm64"     # release body
